INSERT INTO question_category (category_name) VALUES ('Value orientation and sense of responsibility');
INSERT INTO question_category (category_name) VALUES ('Leadership/strategic thinking');
INSERT INTO question_category (category_name) VALUES ('Customer orientation');
INSERT INTO question_category (category_name) VALUES ('Stakeholders management');

INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Guiding principles','In every situation you act according to the guiding principles and corporate policies.','In every situation your underman acts according to the guiding principles and corporate policies.','In every situation your shipmate acts according to the guiding principles and corporate policies.','In every situation your boss acts according to the guiding principles and corporate policies.', 0, true, 1);
INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Positive attitude','You demonstrate positive attitude towards the company as a brand.','Your underman demonstrates positive attitude towards the company as a brand.','Your shipmate demonstrates positive attitude towards the company as a brand.','Your boss demonstrates positive attitude towards the company as a brand.', 0, true, 1);
INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Walking the talk','You walk the talks, keep the promises.','Your underman walks the talks, keeps the promises.','Your shipmate walks the talks, keeps the promises.','Your boss walks the talks, keeps the promises.', 1, true, 1);

INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Making decisions','You make decisions and leads others to act according to TSSK strategy.','Your underman makes decisions and leads others to act according to TSSK strategy.','Your shipman makes decisions and leads others to act according to TSSK strategy.','Your chief makes decisions and leads others to act according to TSSK strategy.', 1, true, 2);
INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Thinking towards customer','In general you think and acts towards others in a customer-oriented manner.','In general your underman thinks and acts towards others in a customer-oriented manner.','In general your shipmate thinks and acts towards others in a customer-oriented manner.','In general your boss thinks and acts towards others in a customer-oriented manner.', 1, true, 3);
INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Further development','You look for ways of further development of existing relationships with customers.','Your underman looks for ways of further development of existing relationships with customers.','Your shipmate looks for ways of further development of existing relationships with customers.','Your boss looks for ways of further development of existing relationships with customers.', 2, true, 3);

INSERT INTO question (title, text_self, text_underman, text_shipmate, text_chief, question_target, valid, question_category_id_question_category) VALUES ('Understanding the needs of stakesholders','You understand the needs of the stakeholders and delivers according to expectations.','Your underman understands the needs of the stakeholders and delivers according to expectations.','Your shipmate understands the needs of the stakeholders and delivers according to expectations.','Your boss understands the needs of the stakeholders and delivers according to expectations.', 1, true, 4);

INSERT INTO employee (admin, academic_title, first_name, surname, email_address) VALUES (true, 'Bc', 'Jakub', 'Ruzicka', 'jakub.ruzicka@student.tuke.sk');
INSERT INTO employee (admin, password, first_name, surname, email_address) VALUES (true, 'password', 'John', 'Doe', 'john.doe@t-systems.com');
INSERT INTO employee (admin, password, first_name, surname, email_address) VALUES (true, 'password', 'Manager', 'Doe', 'manager.doe@t-systems.com');
INSERT INTO employee (admin, password, first_name, surname, email_address) VALUES (false, 'password', 'Duri', 'Manager', 'durisvk2@gmail.com');
INSERT INTO employee (admin, password, first_name, surname, email_address) VALUES (false, 'password', 'Duri', 'Student', 'juraj.carnogursky@student.tuke.sk');

INSERT INTO org_unit (manager_valid_from, manager_valid_to, name, short_name, cost_centre_id_cost_centre, manager_id_employee, parent_id_org_unit) VALUES ('01.01.1999', '01.01.2099', 'TestOrgUnit', '_TEST', null, 3, null);
INSERT INTO org_unit (manager_valid_from, manager_valid_to, name, short_name, cost_centre_id_cost_centre, manager_id_employee, parent_id_org_unit) VALUES ('01.01.1999', '01.01.2099', 'Enterprise of Duri', 'DURIORG', null, 4, null);
UPDATE employee SET org_unit_id_org_unit = 2 WHERE email_address = 'juraj.carnogursky@student.tuke.sk';
